added cellPhone entity
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #15
Opened 2023-08-15 23:49 UTC by Aasish-Virjala

Added cellPhone String variable to User entity.

Closes #9

2023-08-16 01:36 UTC, alecmorrison approved these changes
Solid commenting.... code looks good, follows variable naming convention.

2023-08-17 21:04 UTC, pconrad requested changes

2023-08-17 21:04 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
> +  // added cell phone variable
No need for this comment; please remove it.  Then this is mergeable for 5 pts.
```suggestion
```

2023-08-17 23:29 UTC, pconrad approved these changes
LGTM

2023-08-17 23:29 UTC, merged