adjusted backend and backend testing
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #19
Opened 2023-08-16 07:45 UTC by pabucsb

In this PR I started EPIC: Adjust Ride Request fields to clarify pickup and dropoff. I  renamed the variable room within the entity file in order to avoid confusion. Added new member variables pickupRoom and notes. Adjusted the controller to reflect these changes and also adjusted controller tests.

2023-08-21 22:39 UTC, alecmorrison submitted a review, later dismissed
Looks good!

2023-08-22 03:37 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
> +        //not sure if we have to set dropoffroom and pickuproom
yes, you should, and you did.  So we can remove this comment.
```suggestion
```

2023-08-22 03:38 UTC, pconrad requested changes
One comment to remove, otherwise LGTM

2023-08-22 03:54 UTC, pconrad approved these changes
LGTM

2023-08-22 03:54 UTC, merged