Pablo issue21
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #22
Opened 2023-08-17 01:11 UTC by pabucsb

In this PR I adjusted the frontend in order to reflect the change made to one of my entity variables. 

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/97569267/b9f6699b-f4be-4d83-a828-ac3a20aa6863)

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/97569267/660379b4-365f-48a6-8d67-b2c78e620413)

2023-08-17 21:07 UTC, pconrad commented
@pabucsb Please make the title something descriptive.   

For example: `Add and Rename some fields in Ride entity`

2023-08-21 22:52 UTC, alecmorrison approved these changes
Looks good, other than committing the previous changes

2023-08-22 03:39 UTC, pconrad commented on frontend/src/main/components/Ride/RideTable.js
> +        // }
Why is this commented out?

2023-08-22 03:40 UTC, pconrad commented on frontend/src/main/components/Ride/RideTable.js
> +        // }
Why is this commented out?

2023-08-22 03:40 UTC, pconrad commented on frontend/src/main/components/Ride/RideTable.js
> +        // }
Why are these commented out?

2023-08-22 03:41 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
> +        //not sure if we have to set dropoffroom and pickuproom
See feedback on PR #19

2023-08-22 03:41 UTC, pconrad requested changes
Help me understand why the commented out code is there?

2023-08-22 07:24 UTC, Aasish-Virjala submitted a review, later dismissed
Remove comments, then it looks good.

2023-08-22 07:24 UTC, Aasish-Virjala commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
Remove comment
```suggestion
```

2023-08-23 20:31 UTC, pconrad approved these changes
LGTM

2023-08-23 20:32 UTC, merged