Aasish issue 14
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #23
Opened 2023-08-17 06:52 UTC by Aasish-Virjala

Finished issue 14 tasks. User can edit their phone number from the profile page. Screenshot attached below.

<img width="1512" alt="Screenshot 2023-08-16 at 11 50 43 PM" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/40775364/e598c435-0193-4952-88bd-a0b468af0d98">

<img width="1512" alt="Screenshot 2023-08-16 at 11 52 12 PM" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/40775364/d82fcc97-c82f-4c83-8e9c-ba4aca52a3e9">

Closes #14

2023-08-22 22:05 UTC, pabucsb submitted a review, later dismissed
Looks good to me, just get rid of that one comment.

2023-08-22 22:05 UTC, pabucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
> +  // added cell phone variable
```suggestion

```

2023-08-23 20:34 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +        // console.log(userCellPhone);
```suggestion
```
Remove commented out code

2023-08-23 20:35 UTC, pconrad requested changes
One more comment to remove

2023-08-24 21:31 UTC, Aasish-Virjala commented
Removed all comments and fixed merged conflicts

2023-08-25 01:40 UTC, pabucsb reviewed
LGTM

2023-08-25 07:55 UTC, adhit-s approved these changes
No issues, everything looks fine! Approved!

2023-08-25 20:23 UTC, pconrad approved these changes
LGTM

2023-08-25 20:23 UTC, merged