Made frontend changes to include new entity variables
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #28
Opened 2023-08-18 04:05 UTC by pabucsb

In this PR I made additions to our frontend code in order to give functionality to the new member variables I added in my first PR. 

Link to storybook: https://ucsb-cs156-m23.github.io/proj-gauchoride-m23-9am-1/

2023-08-22 07:00 UTC, Aasish-Virjala requested changes
Just a comment that needs to be removed, otherwise LGTM

2023-08-23 20:35 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
Commented out code?
```suggestion
```

2023-08-23 20:44 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
commented out code?

2023-08-23 20:45 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
commented out code?

2023-08-23 20:47 UTC, pabucsb commented on frontend/src/main/components/Ride/RideForm.js
> +                        //required: "Drop OffRoom number is required."
```suggestion
                        
```

2023-08-24 15:39 UTC, pconrad requested changes
Once again, asking about commented out code.

2023-08-24 21:18 UTC, pconrad approved these changes
LGTM

2023-08-24 21:19 UTC, merged