established placeholder for driver page
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #30
Opened 2023-08-21 01:53 UTC by pabucsb

In this PR I made additions to our frontend and added a placeholder for driver dashboard. The dropdown menu is only visible for those with the driver role. 

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/97569267/4790a8fa-c8b1-4ef0-a129-004a20311a33)

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/97569267/14d887e7-6b24-428e-adec-fc72bf951576)

2023-08-22 06:59 UTC, Aasish-Virjala requested changes
Just remove comments and I think it's good.

2023-08-22 06:59 UTC, Aasish-Virjala commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
Remove comments
```suggestion
```

2023-08-22 06:59 UTC, Aasish-Virjala commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
Remove comments
```suggestion
```

2023-08-22 06:59 UTC, Aasish-Virjala commented on frontend/src/main/components/Ride/RideForm.js
> +                    //})}
```suggestion
```

2023-08-22 06:59 UTC, Aasish-Virjala commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
> +        //not sure if we have to set dropoffroom and pickuproom
```suggestion
```

2023-08-22 21:19 UTC, Aasish-Virjala submitted a review, later dismissed
LGTM

2023-08-25 07:52 UTC, adhit-s approved these changes
Everything looks good. My PR for the rider dashboard will remove the RideForm.js file, but it doesn't seem like this issue is using that so we're in the clear. Approved!

2023-08-25 20:24 UTC, pconrad approved these changes
LGTM

2023-08-25 20:24 UTC, merged