Created controller and controller tests for RiderApplication
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #60
Opened 2023-08-25 10:37 UTC by pabucsb

2023-08-25 11:01 UTC, adhit-s submitted a review, later dismissed
All looks good, glad we spent 5 hours getting mutation coverage to 100% <3

2023-08-25 21:07 UTC, Aasish-Virjala submitted a review, later dismissed
LGTM

2023-08-25 21:41 UTC, Aasish-Virjala approved these changes
LGTM

2023-08-25 21:56 UTC, Aasish-Virjala submitted a review, later dismissed
LGTM not sure why it automatically rejects approval.

2023-08-27 04:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +            Date date = new Date(dateOnly);
This probably should have been factored out into a utility method.  But since this is the last round, I'll let it slide.

2023-08-27 04:04 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER') || hasRole('ROLE_DRIVER') || hasRole('ROLE_MEMBER')")
Only members can create applications.  It makes no sense for a ROLE_USER to have access to this endpoint.

```suggestion
    @PreAuthorize("hasRole('ROLE_MEMBER')")
```

2023-08-27 04:04 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER') || hasRole('ROLE_DRIVER') || hasRole('ROLE_MEMBER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_MEMBER')")
```

2023-08-27 04:09 UTC, pconrad requested changes
So there are a lot of places where the ROLEs authorized to do certain endpoints just don't make sense to me.

The only role that should be able to make an application to be a rider is ROLE_MEMBER.  

Period.   End of story.

There are lots of places where there is a long list of roles.  That's incorrect.   Just ROLE_MEMBER.  No one else.

Then, for reviewing, it should be ROLE_ADMIN. No one else. 

I cannot think of a single reason that any othe role should even be mentioned in the RiderApplicationController.. and I'm not sure what your thinking was.  Let's discuss.

2023-08-27 18:39 UTC, pabucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +    @PreAuthorize("hasRole('ROLE_MEMBER') || hasRole('ROLE_USER') || hasRole('ROLE_DRIVER') || hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ROLE_MEMBER')")
```

2023-08-27 18:40 UTC, pabucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER') || hasRole('ROLE_DRIVER') || hasRole('ROLE_MEMBER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_MEMBER')")
```

2023-08-27 18:42 UTC, pabucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_USER') || hasRole('ROLE_DRIVER') || hasRole('ROLE_MEMBER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_MEMBER')")
```

2023-08-27 18:43 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_in_users_can_get_all_of_theirs() throws Exception {
```suggestion
    public void logged_in_users_cant_get_all_of_theirs() throws Exception {
```

2023-08-27 18:44 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                        .andExpect(status().is(200));
```suggestion
                        .andExpect(status().is(403); 
```

2023-08-27 18:45 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_admin_users_can_get_all_of_theirs() throws Exception {
```suggestion
    public void logged_admin_users_cant_get_all_of_theirs() throws Exception {
```

2023-08-27 18:45 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                            .andExpect(status().is(200));
```suggestion
                            .andExpect(status().is(403)); 
```

2023-08-27 18:45 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_driver_can_get_all_of_theirs() throws Exception {
```suggestion
    public void logged_driver_cant_get_all_of_theirs() throws Exception {
```

2023-08-27 18:45 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                            .andExpect(status().is(200));
```suggestion
                            .andExpect(status().is(403)); 
```

2023-08-27 18:46 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_in_users_can_get_by_id() throws Exception {
```suggestion
    public void logged_in_users_cant_get_by_id() throws Exception {
```

2023-08-27 18:46 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                            .andExpect(status().is(404));
```suggestion
                            .andExpect(status().is(403)); 
```

2023-08-27 18:46 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_in_admins_can_get_by_id() throws Exception {
```suggestion
    public void logged_in_admins_cant_get_by_id() throws Exception {
```

2023-08-27 18:46 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                            .andExpect(status().is(404));
```suggestion
                            .andExpect(status().is(403)); 
```

2023-08-27 18:47 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void logged_in_drivers_can_get_by_id() throws Exception {
```suggestion
    public void logged_in_drivers_cant_get_by_id() throws Exception {
```

2023-08-27 18:47 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +                            .andExpect(status().is(404));
```suggestion
                            .andExpect(status().is(403)); 
```

2023-08-27 18:47 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = {  "MEMBER" })
```

2023-08-27 18:48 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +        public void test_that_logged_in_user_cant_get_by_id_when_the_id_does_not_exist() throws Exception {
```suggestion
        public void test_that_logged_in_members_cant_get_by_id_when_the_id_does_not_exist() throws Exception {
```

2023-08-27 18:48 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +        @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
        @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:48 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:49 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void test_that_all_roles_can_update_their_application() throws Exception {
```suggestion
    public void test_that_all_members_can_update_their_application() throws Exception {
```

2023-08-27 18:49 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void test_that_all_roles_cant_update_others_application() throws Exception {
```suggestion
    public void test_that_all_members_cant_update_others_application() throws Exception {
```

2023-08-27 18:50 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER"})
```

2023-08-27 18:50 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void test_that_all_roles_cant_update_a_nonexistant_application() throws Exception {
```suggestion
    public void test_that_all_members_cant_update_a_nonexistant_application() throws Exception {
```

2023-08-27 18:50 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:51 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void test_that_all_roles_can_create_a_new_application() throws Exception {
```suggestion
    public void test_that_only_members_can_create_a_new_application() throws Exception {
```

2023-08-27 18:51 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:51 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void roles_can_get_all_theirs() throws Exception {
```suggestion
    public void members_can_get_all_theirs() throws Exception {
```

2023-08-27 18:52 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:52 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void any_role_can_cancel_their_application() throws Exception {
```suggestion
    public void members_can_cancel_their_application() throws Exception {
```

2023-08-27 18:53 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:53 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    public void rider_tries_to_cancel_nonexistant_ride_and_gets_right_error_message() throws Exception {
```suggestion
    public void member_tries_to_cancel_nonexistant_ride_and_gets_right_error_message() throws Exception {
```

2023-08-27 18:53 UTC, pabucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
> +    @WithMockUser(roles = { "USER", "MEMBER", "DRIVER", "ADMIN" })
```suggestion
    @WithMockUser(roles = { "MEMBER" })
```

2023-08-27 18:55 UTC, pabucsb reviewed
commit suggestions

2023-08-27 20:03 UTC, pconrad approved these changes
LGTM!

2023-08-27 20:03 UTC, merged