Added GET /api/drivers/all and DriverController + Tests
ucsb-cs156-m23/proj-gauchoride-m23-9am-1 pull request #61
Opened 2023-08-25 11:45 UTC by Aasish-Virjala

In this PR, I added a GET route /api/drivers/all to get a list of all Users that are Drivers. Only logged in Riders, Drivers, and Admins can access this GET route. Screenshot of swagger below.

<img width="1512" alt="Screenshot 2023-08-25 at 4 45 31 AM" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/assets/40775364/1f95ca2f-83f0-452a-a1c0-7babe9c2f158">

2023-08-25 12:29 UTC, Aasish-Virjala commented
Idk why it's showing that 6 files have been changed, even though only 2 have been (DriverController and DriverControllerTests). The other 4 files were from a previous PR but still committed to main, hence why it is showing it, I presume.

2023-08-25 18:00 UTC, pabucsb submitted a review, later dismissed
LGTM

2023-08-25 21:56 UTC, pabucsb submitted a review, later dismissed
LGTM

2023-08-25 21:57 UTC, pabucsb approved these changes
LGTM

2023-08-27 04:11 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
> +}
This is way more complicated than it needs to be.  

```suggestion
    public Iterable<User> drivers()
            throws JsonProcessingException {
        Iterable<User> drivers = userRepository.findAllByDriver(true);
        return drivers;
    }
}
```

2023-08-27 04:14 UTC, pconrad requested changes
The code can be much simpler

2023-08-27 04:16 UTC, merged